"""initial schema

Revision ID: 5ff38378d914
Revises:
Create Date: 2026-02-26 11:42:14.548572

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5ff38378d914"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "academies",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("NOW()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_academies")),
    )
    op.create_table(
        "coaches",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("academy_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("TRUE"), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("NOW()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["academy_id"], ["academies.id"], name=op.f("fk_coaches_academy_id_academies")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_coaches")),
        sa.UniqueConstraint("email", name=op.f("uq_coaches_email")),
    )
    op.create_table(
        "players",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("academy_id", sa.UUID(), nullable=True),
        sa.Column("coach_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("handicap", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column(
            "skill_level",
            sa.String(length=20),
            server_default=sa.text("'beginner'"),
            nullable=False,
        ),
        sa.Column(
            "dominant_hand", sa.String(length=10), server_default=sa.text("'right'"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("NOW()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["academy_id"], ["academies.id"], name=op.f("fk_players_academy_id_academies")
        ),
        sa.ForeignKeyConstraint(
            ["coach_id"], ["coaches.id"], name=op.f("fk_players_coach_id_coaches")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_players")),
        sa.UniqueConstraint("phone", name=op.f("uq_players_phone")),
    )
    op.create_table(
        "progress_snapshots",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("player_id", sa.UUID(), nullable=True),
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.Column("angles_avg_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("consistency_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("total_swings", sa.Integer(), nullable=True),
        sa.Column("coach_notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("NOW()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["player_id"], ["players.id"], name=op.f("fk_progress_snapshots_player_id_players")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_progress_snapshots")),
    )
    op.create_table(
        "videos",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("player_id", sa.UUID(), nullable=True),
        sa.Column("s3_key", sa.String(length=500), nullable=False),
        sa.Column("camera_angle", sa.String(length=20), nullable=True),
        sa.Column("club_type", sa.String(length=30), nullable=True),
        sa.Column(
            "status", sa.String(length=20), server_default=sa.text("'uploading'"), nullable=False
        ),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("fps", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("uploaded_at", sa.DateTime(), server_default=sa.text("NOW()"), nullable=False),
        sa.Column("processed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["player_id"], ["players.id"], name=op.f("fk_videos_player_id_players")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_videos")),
    )
    op.create_table(
        "feedback",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("video_id", sa.UUID(), nullable=True),
        sa.Column("player_id", sa.UUID(), nullable=True),
        sa.Column("coach_id", sa.UUID(), nullable=True),
        sa.Column("feedback_type", sa.String(length=20), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("drill_recommendations", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("priority_fixes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_read", sa.Boolean(), server_default=sa.text("FALSE"), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("NOW()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["coach_id"], ["coaches.id"], name=op.f("fk_feedback_coach_id_coaches")
        ),
        sa.ForeignKeyConstraint(
            ["player_id"], ["players.id"], name=op.f("fk_feedback_player_id_players")
        ),
        sa.ForeignKeyConstraint(
            ["video_id"], ["videos.id"], name=op.f("fk_feedback_video_id_videos")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feedback")),
    )
    op.create_table(
        "frames",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("video_id", sa.UUID(), nullable=True),
        sa.Column("swing_phase", sa.String(length=30), nullable=False),
        sa.Column("frame_number", sa.Integer(), nullable=False),
        sa.Column("s3_key_raw", sa.String(length=500), nullable=True),
        sa.Column("s3_key_overlay", sa.String(length=500), nullable=True),
        sa.Column("s3_key_skeleton", sa.String(length=500), nullable=True),
        sa.Column("keypoints_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("joint_angles_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_reference", sa.Boolean(), server_default=sa.text("FALSE"), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("NOW()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["video_id"], ["videos.id"], name=op.f("fk_frames_video_id_videos")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_frames")),
    )
    op.create_table(
        "comparisons",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("frame_id", sa.UUID(), nullable=True),
        sa.Column("reference_frame_id", sa.UUID(), nullable=True),
        sa.Column("deviation_scores_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("overall_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("ai_feedback_text", sa.Text(), nullable=True),
        sa.Column("coach_feedback_text", sa.Text(), nullable=True),
        sa.Column("coach_approved", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("NOW()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["frame_id"], ["frames.id"], name=op.f("fk_comparisons_frame_id_frames")
        ),
        sa.ForeignKeyConstraint(
            ["reference_frame_id"],
            ["frames.id"],
            name=op.f("fk_comparisons_reference_frame_id_frames"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comparisons")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("comparisons")
    op.drop_table("frames")
    op.drop_table("feedback")
    op.drop_table("videos")
    op.drop_table("progress_snapshots")
    op.drop_table("players")
    op.drop_table("coaches")
    op.drop_table("academies")
    # ### end Alembic commands ###
